Feature/3
gpb-it-factory/sumkin-telegram-bot pull request #3
Opened 2024-05-20 00:50 UTC by Frenchfan

Добавлен первоначальный скелет бота, разработана архитектура приложения таким образом, чтобы упростить дальнейшее масштабирование.

2024-05-20 17:34 UTC, vaganov-vadim requested changes
Особых претензий нет, всё здорово. Пометил пару мест - предмет к обсуждению. И разве что поменять application.properties на application.yml

2024-05-20 17:34 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/configuration/GpbBot.java
> +    public GpbBot(@Value("${token}") String token, CommandsService commandsService) {
Нравится, что токен именно в конструкторе - лайк!

2024-05-20 17:34 UTC, vaganov-vadim commented on README.md
> +### <a id="installation">Установка приложения</a>
За инструкцию также лайк!

2024-05-20 17:34 UTC, vaganov-vadim commented on MiddleService/src/main/resources/application.properties
> +spring.application.name=MiddleService
Давай application.yaml, у нас обычно так принято.

2024-05-20 17:34 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +            log.info("Отправил сообщение \"{}\" получателю {}", message_text, chatId);
Лайк за логирование.

2024-05-20 17:34 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +        this.telegramClient = new OkHttpTelegramClient(token);
Зацепился глаз - иногда так делать нехорошо, но в данной случае в целом вполне ок.

2024-05-20 17:34 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/configuration/GpbBot.java
> +                case PING -> commandsService.sendReply(chatId, "pong");
В плане расширяемости - возможно есть смысл вынести команды и реакцию на них в отдельный класс или хотя бы в Map и передавать его/её в конструкторе. Тогда будет прямо-таки Open-Closed :)

2024-05-21 05:43 UTC, vaganov-vadim commented
+ название PR бы поменять под стандарт :)

2024-05-21 21:13 UTC, Frenchfan commented
поменял имя PR

2024-05-22 17:02 UTC, vaganov-vadim requested changes
Давай пообсуждаем изменения. Комменты выше.

2024-05-22 17:02 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    public void switchService(String message_text, long chatId) {
Не совсем понял, что в итоге мы сделали :) Кажется, что в таком случае нам не особо нужен public sendReply?

2024-05-22 17:02 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    private static final String PING = "/ping";
По сути, скорее всего в этой константе особо нет смысла, потому что она используется буквально в одном месте и вряд ли будет использоваться где-то ещё даже на уровне класса. Можно либо оставить чисто литерал, либо сделать переменной в месте использования. У тебя тут это совсем не критично, просто подсвечиваю на будущее, что часто константами делают то, что особо какой-то специальной константой и не является :)

2024-05-22 19:56 UTC, Frenchfan commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    public void switchService(String message_text, long chatId) {
Вот тут не согласен. SendReply() просто выводит готовый ответ, а вот подготовка этого ответа для других команд (сложнее, чем пинг-понг) будет совсем иной - это основание под наращивание функционала. Да, на этом уровне можно было бы проще написать, но мы же заморачиваемся выносом на уровень сервиса методов, open-closed соблюдаем, как просил. Если я не в ту степь, поправь, пожалуйста.

2024-05-22 19:56 UTC, Frenchfan commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    private static final String PING = "/ping";
ну, команд-то будет больше, уходим от принципа magic number (ну, или тут magic word) - поэтому и в константу. Можно все команды в какой-нибудь list еще кидать, но их у нас будет так мало, что не вижу смысла, можно и несколькими константами обойтись.

2024-05-23 05:36 UTC, vaganov-vadim requested changes
Давай по sendReply разберёмся, чтобы я понял твои мысли и намерения. В остальном всё ок =)

2024-05-23 05:36 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    public void switchService(String message_text, long chatId) {
Я имел в виду, что в таком случае он не должен иметь модификатор public, кажется? Ты его напрямую нигде не используешь.

2024-05-23 05:36 UTC, vaganov-vadim commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    private static final String PING = "/ping";
От того что мы вынесли строчку, используемую в одном месте, в константу и назвали её точно так же - особо никак это на её магичность это не повлияло =) Но это не претензия, просто "на подумать", что не везде это обязательно. В ряде случаев вообще вызывающую команду и её обработку можно инкапсулировать в одном классе и этот вопрос отпадает совсем.

2024-05-23 21:10 UTC, Frenchfan commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    public void switchService(String message_text, long chatId) {
да, согласен - исправил на private

2024-05-23 21:12 UTC, Frenchfan commented on MiddleService/src/main/java/com/gpb/middle/service/CommandsService.java
> +    private static final String PING = "/ping";
решил пока сохранить - просто удобнее править, вот они команды в самом начале класса, визуально выделены из логики метода. Согласен. что функциональных преимуществ тут нет.

2024-05-24 10:48 UTC, vaganov-vadim approved these changes

2024-05-24 12:26 UTC, merged