Задание 4. Добавить базовый CI
gpb-it-factory/sumkin-telegram-bot pull request #6
Opened 2024-05-26 23:22 UTC by Frenchfan

Переструктурировал проект - убрал модульность (не проходил github Actions), добавил Github Actions

2024-05-28 08:22 UTC, vaganov-vadim requested changes
Предлагаю сделать отдельную джобу для тестов, которую потом можно будет расширять.

2024-05-28 08:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/sumkintelegrambot/SumkinTelegramBotApplication.java
> +public class SumkinTelegramBotApplication {
На будущее - несвязанные с самой задачей изменения лучше делать отдельным PR.

2024-05-28 08:22 UTC, vaganov-vadim commented on .github/workflows/gradle.yml
> +  build:
Я понимаю, что по умолчанию в gradle build входят тесты, но давай мы добавим ещё отдельно джобу для тестов, потому что потом её можно обогащать всякими отчётами и другими видами тестов.

2024-05-28 09:58 UTC, Frenchfan commented on src/main/java/com/gpb/sumkintelegrambot/SumkinTelegramBotApplication.java
> +public class SumkinTelegramBotApplication {
Да, согласен, учту.

2024-05-28 18:00 UTC, vaganov-vadim approved these changes

2024-05-29 07:10 UTC, Frenchfan commented
Переструктурировал проект - убрал модульность (не проходил github Actions), добавил Github Actions

2024-05-29 07:11 UTC, merged