Задание 6. Добавить функциональность регистрации пользователя
gpb-it-factory/sumkin-telegram-bot pull request #9
Opened 2024-06-20 19:30 UTC by Frenchfan

- убрал большую часть логирования в аспекты
- сделал классы для всех команд фронтэнда с первоначальной реализацией
- отступил от API в части кода 204 при регистрации - возвращаю 201, чтобы показать внутренний id
- не реализованы тестирование, централизованная обработка исключений (сложности с openfeign), но сделаю чуть позже
- уже многовато для одного пулл реквеста - остальное в следующем

2024-06-25 18:02 UTC, vaganov-vadim commented on .github/workflows/gradle.yml
> +#проверить, можно ли не использовать build
Давай попробуем clean добавить? Такое ощущение, что у тебя какой-то build cache застрял там.

2024-06-25 19:24 UTC, Frenchfan commented on .github/workflows/gradle.yml
> +#проверить, можно ли не использовать build
не помогло

2024-06-26 16:24 UTC, vaganov-vadim requested changes
Привет! В целом всё круто, разве что добавил пару комментов. По CI - надо разобраться, что не так, можно просто попробовать на других ветках поиграть. Если там воспроизводится, то проблема в самом воркфлоу.

2024-06-26 16:24 UTC, vaganov-vadim commented on src/main/java/com/gpb/sumkintelegrambot/configuration/Command.java
>      START("/start", "стартовое сообщение"),
Не уверен в необходимости enum, мы это всё можем хранить в самих командах. А так получается лишняя зависимость между классами.

2024-06-26 16:24 UTC, vaganov-vadim commented on src/main/java/com/gpb/sumkintelegrambot/web/MiddleServiceClient.java
> +    UUID getUserById(@PathVariable Long id);
На будущее - есть смысл для всех возвращаемых значений на стороне миддла предусматривать какую-то DTO'шку, даже если там одно значение. Сегодня только UUID, завтра может добавиться что-то ещё. Добавить необязательный параметр в DTO - неломающее изменение, заменить строчку на объект - ломающее.

2024-07-01 00:47 UTC, Frenchfan commented on src/main/java/com/gpb/sumkintelegrambot/configuration/Command.java
>      START("/start", "стартовое сообщение"),
Это скорее для того, чтобы точно не забыть обработчик команды сделать. Я бы все-таки оставил

2024-07-01 00:49 UTC, Frenchfan commented on src/main/java/com/gpb/sumkintelegrambot/web/MiddleServiceClient.java
> +    UUID getUserById(@PathVariable Long id);
Учел, поменял feign. Кроме того, добавил контейнеризацию (Dockerfile + docker-compose), обработку исключений feign для регистрации, провел рефакторинг

2024-07-01 17:39 UTC, vaganov-vadim commented on src/main/java/com/gpb/sumkintelegrambot/configuration/Command.java
>      START("/start", "стартовое сообщение"),
А что значит не забыть?) Команда = её обработчик

2024-07-01 17:40 UTC, vaganov-vadim approved these changes
Я всё ещё не согласен с Enum, но в целом аппрув :)

2024-07-01 20:39 UTC, merged